// Development-only capture of what the recognition pipeline actually saw.
//
// Every fix in this subsystem so far has been driven by synthetic fixtures that
// I authored, which means each one only tested a failure I had already imagined.
// The 1-finger-as-3 bug survived four such fixtures precisely because none of
// them modelled a hand close to the camera. This module closes that gap: it
// retains the real frames a real camera produced alongside the pipeline's own
// reasoning, so a misread can be replayed deterministically as a test fixture.
//
// Privacy and production safety:
//   * Frames live in a small in-memory ring buffer and nowhere else.
//   * Nothing is written to disk, storage, or the network automatically --
//     export happens only when a developer explicitly calls it.
//   * The recorder is inert unless explicitly enabled, and the app only enables
//     it under import.meta.env.DEV, so production ships the disabled no-op.

// The production recorder. Exported separately so the recognizer can default to
// it WITHOUT importing createDiagnosticsRecorder -- that keeps the capture and
// export machinery reachable only from the import.meta.env.DEV branch, where
// the bundler can drop it entirely rather than shipping it switched off.
export const DISABLED_DIAGNOSTICS = Object.freeze({
  enabled: false,
  record() {},
  last: () => null,
  all: () => [],
  clear() {},
  toFixture: () => null,
});

const BASE64_ALPHABET =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

// Portable base64 so a fixture round-trips identically in the browser (where it
// is captured) and in Node (where it is replayed as a test), without depending
// on btoa or Buffer being present in either.
export function encodeBytes(bytes) {
  let output = '';
  for (let index = 0; index < bytes.length; index += 3) {
    const a = bytes[index];
    const b = index + 1 < bytes.length ? bytes[index + 1] : 0;
    const c = index + 2 < bytes.length ? bytes[index + 2] : 0;
    output += BASE64_ALPHABET[a >> 2];
    output += BASE64_ALPHABET[((a & 3) << 4) | (b >> 4)];
    output +=
      index + 1 < bytes.length ? BASE64_ALPHABET[((b & 15) << 2) | (c >> 6)] : '=';
    output += index + 2 < bytes.length ? BASE64_ALPHABET[c & 63] : '=';
  }
  return output;
}

export function decodeBytes(text) {
  const clean = text.replace(/=+$/, '');
  const bytes = new Uint8ClampedArray(Math.floor((clean.length * 3) / 4));
  let byteIndex = 0;
  let buffer = 0;
  let bits = 0;
  for (const character of clean) {
    const value = BASE64_ALPHABET.indexOf(character);
    if (value === -1) continue;
    buffer = (buffer << 6) | value;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes[byteIndex] = (buffer >> bits) & 0xff;
      byteIndex += 1;
    }
  }
  return bytes;
}

// Strips the pipeline result down to serialisable numbers. Masks and contours
// are deliberately excluded: they are large, and every one of them can be
// regenerated by replaying the frame.
function summarise(result) {
  if (!result) return null;
  return {
    state: result.state ?? null,
    label: result.label ?? null,
    confidence: result.confidence ?? null,
    raisedFingerCount: result.raisedFingerCount ?? null,
    gameValue: result.gameValue ?? null,
    palm: result.palm
      ? { center: { ...result.palm.center }, radius: result.palm.radius }
      : null,
    fingertips: (result.fingertips ?? []).map((tip) => ({
      x: tip.x,
      y: tip.y,
      angle: tip.angle,
      binIndex: tip.binIndex,
      normalizedLength: tip.normalizedLength,
      prominence: tip.prominence,
      curvatureAngle: tip.curvatureAngle,
    })),
    quality: result.quality ?? null,
    diagnostics: result.debug ?? null,
  };
}

export function createDiagnosticsRecorder({ enabled = false, capacity = 8 } = {}) {
  if (!enabled) return DISABLED_DIAGNOSTICS;

  const entries = [];

  return {
    enabled: true,

    record(frame, result, meta = {}) {
      if (!frame) return;
      // Copy: the pipeline reuses frame buffers, so retaining the reference
      // would leave every entry pointing at the same mutated pixels.
      entries.push({
        capturedAt: meta.timestamp ?? null,
        width: meta.width ?? null,
        height: meta.height ?? null,
        frame: new Uint8ClampedArray(frame),
        result: summarise(result),
      });
      while (entries.length > capacity) entries.shift();
    },

    last() {
      return entries.length ? entries[entries.length - 1] : null;
    },

    all() {
      return [...entries];
    },

    clear() {
      entries.length = 0;
    },

    // Serialisable record of one captured frame. Requires an explicit call --
    // nothing leaves memory on its own.
    toFixture(index = -1) {
      const entry = index < 0 ? entries[entries.length + index] : entries[index];
      if (!entry) return null;
      return {
        version: 1,
        width: entry.width,
        height: entry.height,
        capturedAt: entry.capturedAt,
        frameBase64: encodeBytes(entry.frame),
        result: entry.result,
      };
    },
  };
}

// Rebuilds a captured frame so a real-camera misread can be replayed through
// the pipeline in a test, exactly as it occurred.
export function fixtureToFrame(fixture) {
  if (!fixture?.frameBase64) return null;
  const bytes = decodeBytes(fixture.frameBase64);
  const expected = fixture.width * fixture.height * 4;
  if (Number.isFinite(expected) && bytes.length !== expected) {
    throw new Error(
      `Fixture frame is ${bytes.length} bytes but ${fixture.width}x${fixture.height} needs ${expected}.`,
    );
  }
  return bytes;
}
